### ISSUE TITLE
Quarantine Issue with EXIM update - longer Exim IDs

### ISSUE THREAD

**Issue by jbsubs747** [MailCleaner/MailCleaner#585] opened 2024-02-15 15:04 UTC
Hi there,

Picked up issues with all quarantined emails since the upgrade today.  Quarantined emails from before the update works 100%, but the new items cannot be viewed for detail or even force released by clicking on the arrow on the left of the item in the list.  Attaching two screenshots of what we find.  

First screenshot showing no detail when clicking on email.
![20240215 - MC Quarentine Issue_1](https://github.com/MailCleaner/MailCleaner/assets/132551020/9ab8f9eb-45be-406e-9ebe-7d8f0cc2cb6a)

This is the result when clicking on the arrow to force release.
![20240215 - MC Quarentine Issue_2](https://github.com/MailCleaner/MailCleaner/assets/132551020/6abfe0bf-d802-45fb-b412-86627fc23086)

**Comment by JohnMertz** [comment] 2024-02-15 17:32
Hello,

These functions work fine for me on my personal machine and our Cloud cluster:
 
![20240215_10h14m11s_grim](https://github.com/MailCleaner/MailCleaner/assets/6070612/423b8da7-dc7d-459e-99cf-62052f26998b)


Initially, I suspected that it might be the result of using a custom template which had not been updated, but it doesn't look like I actually had to touch any of the template files to make this work. 

Instead, I suspect that it must be caused by a conflict/change to some other the web files (`/usr/mailcleaner/www`).

The second screenshot is related to the `/usr/mailcleaner/bin/force_quarantine.pl` but it seems more likely that this is because the Exim ID is not properly parsed  and left blank in the SOAP request (`20240215/` instead of `20240215/1racDi-0000000001DX-0zs5`). So it is most likely still related to the Web code.

In any case, you should do a `git status` on `/usr/mailcleaner` to see if any files have been modified and if your tree is "up-to-date". There will be "Untracked files" which can generally be ignored, but modifications of tracked files can be a problem.

**Comment by jbsubs747** [comment] 2024-02-15 18:05
Hi John,

Thanks for the quick reply.  I have done a quick git status, but don't see any issues. Have uploaded the screenshot as maybe you can identify something.

<img width="530" alt="image" src="https://github.com/MailCleaner/MailCleaner/assets/132551020/cbce9423-99ad-4579-aa42-c1e5cc5268e7">

Thanks,

**Comment by jbsubs747** [comment] 2024-02-15 18:43
Ok, upon further investigation from the updater4mc.log file the following seems to be the issue.  I have not changed those files so not sure why it complains about them.   

                  ATTENTION: Cannot install Exim 4.97.1
                  
                  Your existing exim configuration template{s):
                  
                  /usr/mailcleaner/etc/exim/exim_stage1.conf_template_4.96
                  /usr/mailcleaner/etc/exim/exim_stage4.conf_template_4.96
                  
                  contain modifications.
                  
                  The modifications will not be carried over to the new template files automatically.
                  
                  Please port your modifications to version of each of these files ending in '_4.97' or confirm that you are okay abandoning these modifications.
                  
                  Once you are statisfied with the state of the '_4.97' templates run the following to force this update:
                  
                    bash /root/Updater4MC/updates/86_mc_exim_4.97.1.update --force

**Comment by JohnMertz** [comment] 2024-02-15 18:54
Was this from a fresh run of `updater4mc.sh`? Or one in your logs?

I had to update the hashes used to verify that the template files were unmodified:
https://github.com/MailCleaner/Updater4MC/commit/688888b80d4eef7bf3b0e15a3c3a39ff0408e5c2

If you have not run the updater since then, running `/root/Updater4MC/updater4mc.sh` now should succeed.

However, if this update has not been applied, it still should not cause this problem. The changes to the `/usr/mailcleaner` should work with both the shorter and longer Exim IDs.

I'm now wondering if it is more likely issue is that you probably are using 4.97.1 (maybe a subsequent update worked? You can check with `dpkg -l | grep mc-exim` or `/opt/exim4/bin/exim --version`) and your browser probably just has some old JavaScript cached. Can your try doing a hard-refresh of the quarantine page (`Ctrl+Shift+R`) or manually clearing the browser cache, then try accessing these functions again?

**Comment by jbsubs747** [comment] 2024-02-15 19:32
Apogies, I think I might have been unclear.  Yes, the logs are from 14th Feb 2024 (yesterday).  I saw the watchdog warning this morning and ran the update manually which worked without errors.  So yes I am on 4.97.1.

You had me excited now as I didn't do a hard-refresh of the quarantine page (Ctrl+Shift+R). I have now tried that and still the same blank page.  Also tried clearing browser cache and trying Edge and Firefox with the same results.

**Comment by JohnMertz** [comment] 2024-02-15 20:53
Oh. Nevermind. I just realized that you were using the Content Quarantine, not the Spam Quarantine. I am able to replicate the issue.

For now, the CLI script should work when provided with the valid ID:

```
/usr/mailcleaner/bin/force_quarantined.pl 20240215/1racDi-000000001DX-0zs5
```

(I think that I got that ID correct, but it was manually copied from your screenshot, so it might be wrong).

The problem is that the ID is not parsed correctly in the admin interface. I should be able to fix that in the next hour or so.

**Comment by jbsubs747** [comment] 2024-02-15 20:57
Hi John,

Excellent.  Thanks for your quick assistance and helpful replies. 

Much appreciated.
JB

**Comment by JohnMertz** [comment] 2024-02-15 21:27
Should be fixed in #586 

You can just do `cd /usr/mailcleaner; git pull` to install the update. Running `/root/Updater4MC/updater4mc.sh` is unnecessary.

Please confirm that this resolves the problem.

**Comment by jbsubs747** [comment] 2024-02-15 21:43
Thanks,

Have updated and tested. Can confirm the fix is working.

**Comment by JohnMertz** [comment] 2024-02-16 01:03
Glad to hear it. Thanks for alerting me!

**Closed by JohnMertz** 2024-02-16 01:03 UTC
