### ISSUE TITLE
MAJOR Tracing display/parsing issue

### ISSUE THREAD

**Issue by WizWareTech** [MailCleaner/MailCleaner#577] opened 2024-02-04 19:34 UTC
Recently I checked my tracing and found it was very messed up. It seems that the code that parses the data from the log files for some reason was chopping up each line into a different arrival date entry row on the tracing display, also breaking the status columns 'Spam status', 'Content status', 'Deliver status', and 'Delivery date', all of which just show dashes in them.

If I expand any of the individual rows, I only see one line of information. In other words, the individual rows do not contain information from a single email any longer. It looks like every row now represents every line of the log.

This makes tracing nearly impossible. I thought that something happened to my install, so I built an entirely new mailcleaner server, and manually set up all the domains on it (which took over an hour). Everything was fine initially, and I thought the issue was resolved. I checked the next day (just now) and it is doing the same thing my original server was doing.

I'm guessing some update came out recently that broke tracing. Can someone PLEASE confirm and help? This is quite a disaster for me.

Attached is a screen shot of what I'm experiencing. Is anyone else?

Another strange thing is the Patch level used to show a date but now shows this:
Version : 2024012501
Patch level : 85-d703c10
![mailcleaner](https://github.com/MailCleaner/MailCleaner/assets/13114/1b04b2dc-a4bd-4b98-b926-6e4e269db120)

**Comment by JohnMertz** [comment] 2024-02-06 04:34
Hi. I suspect that you have mistakenly updated the `mc-exim` package to 4.97.1. We discourage updates outside of the provided Updater4MC scripts. However, this was mostly may mistake for having made that version of the new package public. I anticipated that we were going to release it already, but we decided to put it off until we have more hands on deck to deal with possible issues.

I suspect this because we had this exact problem while testing the new version. The problem is fixed in [this PR](https://github.com/MailCleaner/MailCleaner/pull/573),  but it is not yet merged.

There's really 2 options to help you immediately:
* Downgrade to Exim 4.96.2: `apt-get install mc-exim:4.96.1`. Howevever, this will not fix the tracing or `search_log.pl` script for any messages that already have 23-character long IDs.
* You can checkout the existing PR branch: 
```
cd /usr/mailcleaner
git fetch origin pull/573/head:exim-4.97.1
git checkout exim-4.97.1
bin/mc_mysql -s mc_spool </usr/mailcleaner/install/dbs/t_sp_spam.sql
bin/check_db.pl -s --dbs=mc_spool --update
bin/check_db.pl -s --dbs=mc_spool --myrepair
```

I would recommend the latter. We have been using this on our Cloud service for a couple of weeks with no complaints, and I've been using it on my personal machine for longer than that.

 I can update the issue when the PR is merged and include instructions to get you back to the master branch so that future updates work as expected.
 
Sorry for the inconvenience. I have since un-published the new version, so it should not be possible for others to install it.

**Comment by xzenor** [comment] 2024-02-06 11:31
Hi @JohnMertz, Sadly the update was installed here as well before you could un-publish the new version.  

If we checkout the pr-branch, wouldn't that mess with future updates? We're still debating about trying your solution or just rolling back from a backup with the risk of having everything that was in the queue being resent.

**Comment by JohnMertz** [comment] 2024-02-06 14:30
Hi. Sorry to hear that.

It will prevent future updates, but this should be the next major change that will be merged, so you won't really miss anything important.

When the PR is merged, you will be able to `git checkout master` and `git pull --rebase origin master` to get back on track so that future updates will work.

It's best to do one or the other quickly since the longer IDs cannot be written to the DB for quarantined items as is.

**Comment by WizWareTech** [comment] 2024-02-06 18:39
John, I thought I was going crazy and I can't tell you how happy I am to see it wasn't something I was doing. I have spent probably 20 hours reinstalling/testing/troubleshooting this issue over the past week. This is a relief.

On another note, I am having a big problem with something else now, after all I've been through with this tracing issue. Since you were incredibly helpful with the above issue, could you by any chance help me with this one too: https://github.com/MailCleaner/MailCleaner/issues/578

**Comment by JohnMertz** [comment] 2024-02-07 18:23
Sorry about that. The version in the regular text was correct (4.96.2), but the version in the code snippet was wrong (4.96.1). I correct that. Glad you figured it out.

**Comment by xzenor** [comment] 2024-02-07 21:37
No apologies necessary, John. I just wrote my findings and workflow for anyone else ending up here :)

**Comment by JohnMertz** [comment] 2024-02-13 20:09
Exim 4.97.1 commits for MailCleaner and Updater4MC are now merged and package is re-published in repo.

Anyone who manually checked out these commits should checkout `master` again for both and run Updater4MC:

```
cd /usr/mailcleaner/; git checkout master; cd /root/Updater4MC; git checkout master; /root/Updater4MC/updater4mc.sh
```

Failing to do this will prevent future updates.

I'm closing this issue, but feel free to let me know in a new issue if any problems are encountered as a result of the new Exim version.

**Closed by JohnMertz** 2024-02-13 20:09 UTC
