### ISSUE TITLE
No fail2ban DB entries since update to mailcleaner-library 1.1.3

### ISSUE THREAD

**Issue by bogdankruszewski** [MailCleaner/MailCleaner#600] opened 2024-04-09 16:20 UTC
Hi @JohnMertz , hi community,

I've noticed, that since the update of mailcleaner-library to 1.1.3 from 10th Jan 2024 (https://github.com/MailCleaner/Updater4MC/commit/514eff7162e442f5647ed340c3ff9e0c6285da2d) our MailCleaner cluster doesn't write new entries to the fail2ban_ips table anymore, neither on the master node nor on the slave.

Fail2ban is working generelly and you can see a lot of blocked IPs with ipset list, but because of this issue, this list is not persistent and is not synchronized between master and slave node (every node has his "own" ipset list).

Can someone tell me, where to troubleshoot this issue and give me a hint, if it's only happens in our environment or also in others?
I've already downloaded the mailcleaner-library v 1.1.3 and compared it to the previous one, but I have currently no testing system to play around and find our, which changes of the library are causing this issue.

Best regards

Bogdan

**Comment by Brauadler** [comment] 2024-04-10 05:44
There are no more entries for me since the mentioned update. I have also noticed that I am no longer able to manually ban an IP via the CLI. Sometimes after the update it had worked with `fail2ban.py ban -j mc-exim -i X.X.X.X` or with the variant + `--f2b-call`. However, I'm not entirely sure about this, as there are always error messages in the logs and restarts only help to a limited extent. There are also error messages with the automatic unbans and initiations of the jails after restarts.

Log entry of an automatic ban, but a manual one produces the same entry :
> 2024-04-09 16:29:11,143 fail2ban.actions[44699]: WARNING [mc-exim-1y] Ban X.X.X.X
2024-04-09 16:29:11,150 fail2ban.actions.action[44699]: ERROR   ipset add mc-exim-1y X.X.X.X && PYENV_VERSION=3.7.7 fail2ban.py ban -j mc-exim-1y -i X.X.X.X returned 7f00

Since the ipset is still full, I assume that destroying and recreating it does not work:

> 2024-03-25 22:30:58,148 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-ssh-1y returned 7f00
> 2024-03-25 22:30:59,032 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-webauth-1d returned 7f00
> 2024-03-25 22:30:59,862 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-exim-1d returned 7f00
> 2024-03-25 22:31:00,104 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-webauth-1m returned 7f00
> 2024-03-25 22:31:00,619 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-exim-1m returned 7f00
> 2024-03-25 22:31:01,129 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-ssh-1w returned 7f00
> 2024-03-25 22:31:01,900 fail2ban.actions.action[122393]: ERROR   ipset destroy mc-webauth-1w returned 7f00
> 2024-03-25 22:31:04,643 fail2ban.actions.action[44699]: ERROR   ipset create mc-exim-1d hash:ip returned 7f00
> 2024-03-25 22:31:04,645 fail2ban.actions.action[44699]: ERROR   ipset create mc-exim-1m hash:ip returned 7f00
> 2024-03-25 22:31:04,647 fail2ban.actions.action[44699]: ERROR   ipset create mc-exim-1w hash:ip returned 7f00
> 2024-03-25 22:31:04,649 fail2ban.actions.action[44699]: ERROR   ipset create mc-exim-1y hash:ip returned 7f00
> 2024-03-25 22:31:04,651 fail2ban.actions.action[44699]: ERROR   ipset create mc-ssh-1d hash:ip returned 7f00
> 2024-03-25 22:31:04,653 fail2ban.actions.action[44699]: ERROR   ipset create mc-ssh-1m hash:ip returned 7f00
> 2024-03-25 22:31:04,654 fail2ban.actions.action[44699]: ERROR   ipset create mc-ssh-1w hash:ip returned 7f00
> 2024-03-25 22:31:04,656 fail2ban.actions.action[44699]: ERROR   ipset create mc-ssh-1y hash:ip returned 7f00
> 2024-03-25 22:31:04,657 fail2ban.actions.action[44699]: ERROR   ipset create mc-webauth-1d hash:ip returned 7f00
> 2024-03-25 22:31:04,658 fail2ban.actions.action[44699]: ERROR   ipset create mc-webauth-1m hash:ip returned 7f00
> 2024-03-25 22:31:04,660 fail2ban.actions.action[44699]: ERROR   ipset create mc-webauth-1w hash:ip returned 7f00
> 2024-03-25 22:31:04,661 fail2ban.actions.action[44699]: ERROR   ipset create mc-webauth-1y hash:ip returned 7f00
> 2024-03-25 22:31:21,342 fail2ban.filter [44699]: ERROR   Error in FilterPyinotify callback: 'module' object has no attribute '_strptime_time'
> 2024-03-25 22:31:21,342 fail2ban.filter [44699]: ERROR   Error in FilterPyinotify callback: 'module' object has no attribute '_strptime_time'
> 2024-03-25 22:31:21,342 fail2ban.filter [44699]: ERROR   Error in FilterPyinotify callback: 'module' object has no attribute '_strptime_time'

**Comment by Brauadler** [comment] 2024-05-15 10:43
Fail2ban in debugmode unfortunately does not give any hints why no DB entry is created, neither by fail2ban itself, nor by manual banning. Calling the function with `--db-insert` does not lead to an entry of the IP in the DB either. 

On the other topic: According to my observations, the entries in `/var/log/fail2ban.log` change from code **100** to code **7f00** after a unattended nightly restart of the services (tolaunch.always) by the update4mc routine triggered by an update. Is it normal that both log variants are written as ERROR in the log file?

This is the only hint i found in the fail2ban/server/action.py in the Github repository: 
```
_RETCODE_HINTS = {
	0x7f00: '"Command not found".  Make sure that all commands in %(realCmd)r '
	        'are in the PATH of fail2ban-server process '
			'(grep -a PATH= /proc/`pidof -x fail2ban-server`/environ). '
			'You may want to start '
			'"fail2ban-server -f" separately, initiate it with '
			'"fail2ban-client reload" in another shell session and observe if '
			'additional informative error messages appear in the terminals.'
```

If I manually trigger the update4mc routine with a pending Github update, the return code is strangely not changed and the ban continues to work. 
To fix the problem temporarily and at least get bans back into the IPsets without an entry in the DB I have to run `/usr/mailcleaner/etc/init.d/firewall restart` manually. I have not yet tried calling `/usr/mailcleaner/etc/init.d/fail2ban` directly.

**Comment by JohnMertz** [comment] 2024-05-15 16:01
Hi,

Thanks for looking into this. Unfortunately the team member who wrote the Fail2Ban integration is no longer working with us. I've only learned just enough to do the maintenance required and it is very likely that I've introduced at some point. I haven't really had time to investigate this specific issue. However, I do think that I see the same behaviour. We have lots of DB entries, but the most recent 'last_hit' is from January.

Regarding the fact that restarting the firewall fixes it, I suspect that it is probably a problem in the order of operations after the update script. The service restarts were defined before fail2ban was bolted on as a child process of `firewall`, so it is likely that, fail2ban may have dependencies that are not satisfied. When the firewall is restarted manually, this is probably not the case. That's complete speculation, without looking at the code.

I think I have a little bit of time to look at this, so I'll start by comparing changes to 1.1.3 (and accompanying changes to this repo, if there were any).

**Comment by JohnMertz** [comment] 2024-05-16 02:20
I have 2 PRs waiting to merge (https://github.com/MailCleaner/Updater4MC/pull/93 and #608), but since it is past the end of the workday, I'm not going to merge them until tomorrow. The former is an update to the mailcleaner-library which makes the ban and unban actions follow a bit more straight-forward of a procedure. This also eliminates the need to call the `ipset` commands directly within the `action.d/mc-ipset.conf` action definition, since it will be called as part of the `fail2ban.py` command, so the latter removes that.

I'm testing it on our Cloud cluster right now and items do appear to be added to the DB successfully.

If you wanted to try yourself, you can modify the `mc-ipset.conf` yourself and install the new version of the library, which is already public:

```
cd /var/mailcleaner/.pyenv
su - mailcleaner -c "/var/mailcleaner/.pyenv/shims/pip3 install --upgrade mailcleaner-library -U --trusted-host repository.mailcleaner.net --index https://repository.mailcleaner.net/python/ --extra-index https://pypi.org/simple/"
```

Assuming nothing changes with the deployed version of 1.1.5, you won't need to do anything when the PRs are merged, but you will need to revert the change to `mc-ipset.conf` in order to allow Updater4MC to run without being blocked by the conflict.

If you are okay waiting, then simply running `/root/Updater4MC/updater4mc.sh` after the 2 PRs are merged, or waiting for the automatic update will hopefully resolve the issue.

**Comment by Brauadler** [comment] 2024-05-17 06:54
Hello @JohnMertz,

i can confirm that the entries in the database are working again. The correct restart of the manual ban function after the unattended update also worked. Thanks for the fail2ban update

**Comment by bogdankruszewski** [comment] 2024-05-17 12:23
Hi @JohnMertz,

I can also confirm, that Fail2ban started to work correctly and is adding IPs to the DB on master and slave node since the latest update.

Best regards

Bogdan

**Comment by JohnMertz** [comment] 2024-05-18 00:24
Cheers!

Thanks for noticing and keeping on top of the issue!

**Closed by JohnMertz** 2024-05-18 00:24 UTC
